### ISSUE TITLE
给大佬磕一个

### ISSUE THREAD

**Issue by book572** [Szy-XianQi/Szy_pvzHE_cheat#3]
请问大佬，v2.2版本能用吗？您后续会出融合版的修改器吗？期待ing

**Comment by Szy-XianQi** [comment]
最近比较忙 有空会跟随游戏版本更新

**Comment by book572** [comment]
> 最近比较忙 有空会跟随游戏版本更新

好的，谢谢大佬！期待融合版的修改器~~~~~~
