### ISSUE TITLE
2.5.1修改随机盒子必报错是啥原因呢大佬！

### ISSUE THREAD

**Issue by Kequans** [Szy-XianQi/Szy_pvzHE_cheat#4]
测试了一下，2.5.1版本的随机盒子必然闪退！
2.5及以下版本可以正常使用！
![QQ_1727373680933](https://github.com/user-attachments/assets/3e90ee6a-16a7-4de8-80ae-5c132d7ea52d)

**Comment by Szy-XianQi** [comment]
因为2.5.1我还没更新，没关注游戏作者没想到更新那么快 今天更吧

**Comment by Kequans** [comment]
> 因为2.5.1我还没更新，没关注游戏作者没想到更新那么快 今天更吧

大佬牛！

**Comment by Szy-XianQi** [comment]
有想法可以提我尽量去做
