### ISSUE TITLE
大佬请问盲盒僵尸怎么提高出现巨人的概率？

### ISSUE THREAD

**Issue by Jimbo6p** [Szy-XianQi/Szy_pvzHE_cheat#5]
比如五个盲盒僵尸里必出两个巨人或者三个巨人啥的

**Comment by Szy-XianQi** [comment]
盲盒僵尸是?砸罐子吗

**Comment by Jimbo6p** [comment]
普通僵尸变礼盒僵尸，然后礼盒僵尸可以开出任何僵尸，能不能修改礼盒僵尸出僵尸的概率？
![Snipaste_2024-10-02_16-31-15](https://github.com/user-attachments/assets/a0bebb11-b24e-46e1-b725-75766f904fd6)

**Comment by Szy-XianQi** [comment]
call 5AF400 游戏内的随机数函数 返回给eax一个[0, eax)的随机值 然后根据cmpeax做不同跳转就行了

**Comment by Jimbo6p** [comment]
作者的修改器功能已经非常强大了，能控制盒子指定出任何植物，但有个小缺点就是不能随心所欲的控制每一个盒子，如果僵尸板块也有礼盒僵尸指定就更完美了！
